### ISSUE TITLE
Unable to buy you a coffee with PayPal

### ISSUE THREAD

**Issue by chowlett** [bobbyhadz/aws-amplify-react-auth#3]
:-)

@bobbyhadz you mentioned that your buymeacoffee creator account is linked to PayPal. So I expect to see a PayPal option, but I'm not seeing it. Here is a screenshot:

![image](https://user-images.githubusercontent.com/969735/144438957-2a84cb49-73e9-41aa-8486-4da3291a36c1.png)

In case geography matters, I am in Canada.

**Comment by bobbyhadz** [comment]
Yeah, I actually sent them an email and got a response that they decided to discontinue supporting Paypal without informing their users. This blows my mind.
![bmc-email](https://user-images.githubusercontent.com/25652656/144439774-320c099f-9430-4b4f-9b61-e83c87d652b1.png)
Thank you for letting me know, they certainly didn't.
You don't have to, but if you insist to buy me a coffee I have a direct Paypal link, not sure if it works in Canada - [https://www.paypal.com/paypalme/bobbyhadz](https://www.paypal.com/paypalme/bobbyhadz)

**Comment by albusphan** [comment]
hi @bobbyhadz , do you have other payment, or binance account :D, casue I'm from Vietnam
Really thank you alot about all the cdk stuffs 😄

**Comment by bobbyhadz** [comment]
Hi @albusphan 
My business started picking up, so I don't take donations anymore but thanks and glad the articles helped.
Thank you for reading!
